version = 0.1

[default.deploy.parameters]
stack_name = "atushome-backend"
resolve_s3 = true
s3_prefix = "atushome-backend-v2"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "FromEmail=\"adminatush@gmail.com\""
image_repositories = []
disable_rollback = false

[default.global.parameters]
region = "eu-west-1"
